language: python

sudo: false

os: linux
dist: trusty

# whitelist
branches:
  only:
    - master
    - dev

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

git:
    submodules: false

matrix:
  include:
    ##########################################################################
    # Clang on Linux
    ##########################################################################

    # Clang 3.6
    - env:
      - COMPILER=clang++-3.6
      - BUILD_TYPE=Coverage
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - g++-5
            - python3.5
            - python3.5-dev
            - python2.7
            - python2.7-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
      python: 2.7

    - env:
        - COMPILER=clang++-3.6
        - BUILD_TYPE=Release
      addons: *clang36
      python: 2.7

    - env:
        - COMPILER=clang++-3.6
        - BUILD_TYPE=Release
      addons: *clang36
      python: 3.5

    # Clang 3.7
#    - env:
#      - COMPILER=clang++-3.7
#      - BUILD_TYPE=Coverage
#      addons: &clang37
#        apt:
#          packages:
#            - clang-3.7
#            - g++-5
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#
#    - env:
#      - COMPILER=clang++-3.7
#      - BUILD_TYPE=Release
#      addons: *clang37
#
#    # Clang 3.8
#    - env:
#      - COMPILER=clang++-3.8
#      - BUILD_TYPE=Coverage
#      addons: &clang38
#        apt:
#          packages:
#            - clang-3.8
#            - g++-5
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#
#    - env:
#      - COMPILER=clang++-3.8
#      - BUILD_TYPE=Release
#      addons: *clang38

    # Clang 3.9
    - env: COMPILER=clang++-3.9 BUILD_TYPE=Coverage
      addons: &clang39
        apt:
          packages:
            - clang-3.9
            - g++-5
            - python3.5
            - python3.5-dev
            - python2.7
            - python2.7-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
      python: 2.7

    - env:
      - COMPILER=clang++-3.9
      - BUILD_TYPE=Release
      addons: *clang39
      python: 2.7

    - env:
      - COMPILER=clang++-3.9
      - BUILD_TYPE=Release
      addons: *clang39
      python: 3.5

    # Clang 4.0
    - env:
      - COMPILER=clang++-4.0
      - BUILD_TYPE=Coverage
      addons: &clang40
        apt:
          packages:
            - clang-4.0
            - g++-5
            - python3.5
            - python3.5-dev
            - python2.7
            - python2.7-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
      python: 2.7

    - env:
      - COMPILER=clang++-4.0
      - BUILD_TYPE=Release
      addons: *clang40
      python: 2.7

    - env:
      - COMPILER=clang++-4.0
      - BUILD_TYPE=Release
      addons: *clang40
      python: 3.5

    # Clang 5.0
    - env:
      - COMPILER=clang++-5.0
      - BUILD_TYPE=Coverage
      addons: &clang50
        apt:
          packages:
            - clang-5.0
            - g++-5
            - python3.5
            - python3.5-dev
            - python2.7
            - python2.7-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      python: 2.7

    - env:
      - COMPILER=clang++-5.0
      - BUILD_TYPE=Release
      addons: *clang50
      python: 2.7

    - env:
      - COMPILER=clang++-5.0
      - BUILD_TYPE=Release
      addons: *clang50
      python: 3.5

    ##########################################################################
    # GCC on Linux
    ##########################################################################

    # GCC 5
    - env:
      - COMPILER=g++-5
      - BUILD_TYPE=Coverage
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - python3.5
            - python3.5-dev
            - python2.7
            - python2.7-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
      python: 2.7

    - env:
      - COMPILER=g++-5
      - BUILD_TYPE=Release
      addons: *gcc5
      python: 2.7

    - env:
      - COMPILER=g++-5
      - BUILD_TYPE=Release
      addons: *gcc5
      python: 3.5

#    # GCC 6
#    - env:
#      - COMPILER=g++-6
#      - BUILD_TYPE=Coverage
#      addons: &gcc6
#        apt:
#          packages: g++-6
#          sources:
#            - ubuntu-toolchain-r-test
#
#    - env:
#      - COMPILER=g++-6
#      - BUILD_TYPE=Release
#      addons: *gcc6


    - env:
      - COMPILER=g++-7
      - BUILD_TYPE=Coverage
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - python3.5
            - python3.5-dev
            - python2.7
            - python2.7-dev
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
      python: 2.7

    - env:
      - COMPILER=g++-7
      - BUILD_TYPE=Release
      addons: *gcc7
      python: 2.7

    - env:
      - COMPILER=g++-7
      - BUILD_TYPE=Release
      - RELEASE_MAKER=true
      addons: *gcc7
      python: 3.5


before_install:
    - export CXX=$COMPILER
    - $COMPILER --version
    - python --version

install:
    - python -m pip install pytest numpy

before_script:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive --depth=50

script:
    - git clone https://github.com/sizmailov/pyxmopp_tests_dataset.git tests_dataset
    - python setup.py install
    - python -m pytest pytests

after_success:
    - python -m pip install gcovr
    - gcovr cmake-build-coverage --root=./ --delete --exclude='external/.*' --exclude='tests/.*' --xml -o coverage.xml
    - bash <(curl -s https://codecov.io/bash)
    - if [ "$TRAVIS_BRANCH" == "master" ]  && [ $RELEASE_MAKER ]; then
        DO_GH_PAGES=true;
        DO_PYPI_RELEASE=true;
      fi;
    - if [ "$TRAVIS_BRANCH" == "dev" ]  && [ $RELEASE_MAKER ]; then
          DO_PYPI_PRERELEASE=true;
      fi;

before_deploy:
  - bash build_docs.sh
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"


deploy:
  - provider: pages
    verbose: true
    local-dir: docs/build/html
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    on:
      tags: false
      branch: master
      condition: $DO_GH_PAGES

  - provider: pypi
    user: sizmailov
    server: https://test.pypi.org/legacy/ # Remove for deployment to official PyPi repo
    password:
      secure: "Nl30LxQNGWXsNTqMBwjHY9CAfDks4reOk0wV89iWjCK+4KjX3dwoa4vB0L+j/a0v8qAHSnwQYfNaFBWnUycwqgViOiDePEp8orM3UCxji/QSVFQ3oQQd6Xxzzpgem/N0pcyhf540xRypAnQyfOZP7vsRnvMyU3s8xRn3Vhws64niZGFtt7MaMfz/dew74ji3+nYrJdZTnuGXXj5oazUArxalVbO7Er3yNYTPEpZ4mo1+6PJEJrPqCyTkYBIRLv5F/JiX37wNv1CF2uKN9QtmB1folC266I5cEAZORvR5TEdP9RQrV32tv0kqt+bLnAFeV0x0zGlVYurgchXyiw3MsW1tPzZlVehjLqKOGxpoPAbZBclsIUfCy5ZG5Dj3qZ/kf2XlP9u+loqYqKMeAVoGNwwYCcZDY98C4RGdvW1AF96JJRLiMtPd3W8bB2lx2MeJRbN1BTDWy0C23NJ9/oluBO3LEBJk6RFZFDlB96viGPr/0Pd05RFPa7bKrdUApShue1AbmyVkDkT263f9Knbdh1VcJVxyoa0Jtg3qIofsdk2hvSKY+UkA3TO8f2Q3WHPIDFQPyLVSL4vNtZ7URdz9HnBKh/sQqWX3ssfOB7hXhCqjmUQ0af9PVUc689Vl2Z2TJKq2RREwDvJJBuQdTEF4ErxNXwwPdN4UG9ys+3Gg7ek="
    distributions: "sdist"
    skip_existing: true
    on:
      branch: dev
      condition: $DO_PYPI_PRERELEASE

  - provider: pypi
    user: sizmailov
    password:
      secure: "cr7uoS3mUnPOCqhwORZ8B+eqMYcejNSZPLpTzE2/oCbmoWgVT6Rb9k+NTFzmWc9KzfLnxYljSOKCXQ92qp1zQvgV7bcqjQjNj8SOdfSndVIGmy3PKLqxuQyo11mecMH2JgPoK8bVHJtxjFjml/jmx6jXTspYlvSFqiDl7t6rXjSKbDpMtePGrmhAnixD1Qw1PodrMzZ4vhcKlpTCn0rb+jmCkAQczRjgvUkB4PUCMB5L1940/LVbLpA7S59nKKgFmPUD6djPk6QqqjK22z2qSFe8EIC0jrN0q1B/U2WGEYHceEByR9PKTwA828i0/RSuslNzVA199VFiDCvPZ/1G1vIysdZ9VdMSpyR/dEZ9AOR2CvdELuf7hGrT4xIck5i1RjjGu2fFQ6p8p8rGJ20czQJp6gMBpVwAVRM6KF9Fv0oH5Xtok9nZXJCzIZ2CpDl/Cu+6+ZK6wIseflJslKvTGY4sJG9sXza54GMBuoQEBHEih3PZ1QLE1ViLnAbQJ04auSqtODuoUkvA/1HY7Z7p48TKJFBT6rAEnihRp755ZtgB7FaKsKK2Kge3BETVdMYw48yrxoZ4RqpEDKcv+8YsoaEOlT2oAJ+8ikpFECl+q9Oc04D4fDRc4Ds33XBdDMwV+rfUMUiFZuvyFo+ACBzo+SOv+izmnTpSNYEvk1UN0+E="
    distributions: "sdist"
    skip_existing: true
    on:
      branch: master
      condition: $DO_PYPI_RELEASE



